(()=>{
'use strict';
const $=id=>document.getElementById(id),form=$("articleForm");
if(!form||!window.supabase)return;
const U='https://qyipadinsphoyxotrceo.supabase.co',K='sb_publishable_S73dZK9ro03lWDbHFzZhw_5t5pDtGt';
const db=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const f={title:$("title"),category:$("category"),author:$("author"),excerpt:$("excerpt"),content:$("content"),publishedAt:$("publishedAt"),files:$("imageFile")};
let editingId=null,busy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const note=(t,c='')=>{const e=$("articleMessage");if(e){e.textContent=t;e.className=`message ${c}`}};
const tags=()=>String($("ppwTags")?.value||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).slice(0,12);
function addUI(){const grid=form.querySelector('.form-grid');if(!grid||$("ppwTags"))return;const a=document.createElement('label');a.className='full';a.innerHTML='Topics / Tags<input id="ppwTags" maxlength="250" placeholder="sports, student life, campus"><span class="help">Separate tags with commas.</span>';grid.appendChild(a);const b=document.createElement('label');b.className='full';b.innerHTML='Schedule publication<input id="ppwSchedule" type="datetime-local"><span class="help">Scheduled stories automatically publish when their time arrives.</span>';grid.appendChild(b);const tools=document.createElement('div');tools.className='ppw-admin-tools';tools.innerHTML='<button id="ppwPreview" class="secondary-btn" type="button">Preview</button><span id="ppwAutoStatus">Autosave is on</span>';form.querySelector('.form-actions')?.before(tools);const filter=document.createElement('div');filter.className='ppw-admin-filter';filter.innerHTML='<input id="ppwArticleSearch" type="search" placeholder="Search your articles..."><select id="ppwStatusFilter"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Drafts</option><option value="scheduled">Scheduled</option></select>';document.querySelector('.articles-panel .panel-heading')?.after(filter);const stats=document.createElement('div');stats.id='ppwNewsroomStats';stats.className='ppw-newsroom-stats';document.querySelector('.articles-panel')?.prepend(stats)}
async function session(){const {data}=await db.auth.getSession();if(!data.session)throw Error('Your session expired. Please sign in again.');const {data:r,error}=await db.from('admin_roles').select('role').eq('user_id',data.session.user.id).maybeSingle();if(error||!r?.role)throw Error('Your newsroom permissions could not be verified.');return r.role}
async function upload(file){if(file.size>6*1024*1024)throw Error(`${file.name} is larger than 6 MB.`);const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),safe=['jpg','jpeg','png','webp','gif'].includes(ext)?ext:'jpg',path=`articles/${crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}.${safe}`;const {data,error}=await db.storage.from('article-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw Error(`Image upload failed: ${error.message}`);return db.storage.from('article-images').getPublicUrl(data.path).data.publicUrl}
async function save(status){await session();const title=f.title.value.trim(),body=f.content.value.trim();if(!title||!body)throw Error('Please enter both a headline and the article text.');const schedule=$("ppwSchedule")?.value?new Date($("ppwSchedule").value):null;if(schedule&&Number.isNaN(schedule.getTime()))throw Error('Please choose a valid schedule time.');const scheduled=!!(schedule&&schedule>new Date());const actual=status==='published'&&scheduled?'scheduled':status;const files=[...f.files.files];let current=null;if(editingId){const r=await db.from('articles').select('*').eq('id',editingId).single();if(r.error)throw r.error;current=r.data}let image=current?.image_url||null;if(files[0])image=await upload(files[0]);const slugify=v=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,90);const data={title,slug:current&&current.title===title?current.slug:slugify(title),excerpt:f.excerpt.value.trim(),content:body,category:f.category.value,author:f.author.value.trim()||'PPW Staff',image_url:image,published_at:actual==='published'?(schedule?schedule.toISOString():new Date().toISOString()):null,scheduled_at:schedule?schedule.toISOString():null,status:actual,tags:tags(),updated_at:new Date().toISOString()};let result=editingId?await db.from('articles').update(data).eq('id',editingId):await db.from('articles').insert(data).select('id').single();if(result.error)throw result.error;const id=editingId||result.data.id;if(files.length){const old=await db.from('article_images').select('sort_order').eq('article_id',id).order('sort_order',{ascending:false}).limit(1);let next=(old.data?.[0]?.sort_order??-1)+1;const rows=[];for(let i=files[0]?1:0;i<files.length;i++){const url=await upload(files[i]);rows.push({article_id:id,image_url:url,sort_order:next++,alt_text:title})}if(rows.length){const r=await db.from('article_images').insert(rows);if(r.error)throw r.error}}if(actual==='published'){const r=await db.from('articles').update({featured:false}).neq('id',id);if(r.error)throw r.error;const x=await db.from('articles').update({featured:true}).eq('id',id);if(x.error)throw x.error}return actual}
function clearDraft(){localStorage.removeItem('ppw-admin-draft-v2')}
function reset(){form.reset();editingId=null;clearDraft();if($("ppwTags"))$("ppwTags").value='';if($("ppwSchedule"))$("ppwSchedule").value='';if($("editorHeading"))$("editorHeading").textContent='Create Article';if($("cancelEditBtn"))$("cancelEditBtn").classList.add('hidden');if($("author"))$("author").value='PPW Staff'}
function autosave(){if(editingId)return;const data={title:f.title.value,category:f.category.value,author:f.author.value,excerpt:f.excerpt.value,content:f.content.value,tags:tags(),schedule:$("ppwSchedule")?.value||'',savedAt:Date.now()};if(!data.title&&!data.content)return;localStorage.setItem('ppw-admin-draft-v2',JSON.stringify(data));if($("ppwAutoStatus"))$("ppwAutoStatus").textContent=`Autosaved ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`}
function restore(){try{const d=JSON.parse(localStorage.getItem('ppw-admin-draft-v2')||'null');if(!d||Date.now()-d.savedAt>604800000||f.title.value||f.content.value)return;f.title.value=d.title||'';f.category.value=d.category||'School News';f.author.value=d.author||'PPW Staff';f.excerpt.value=d.excerpt||'';f.content.value=d.content||'';if($("ppwTags"))$("ppwTags").value=(d.tags||[]).join(', ');if($("ppwSchedule"))$("ppwSchedule").value=d.schedule||'';note('Recovered an unsaved local draft. Save it when ready.','success')}catch{}}
function preview(){const w=window.open('','_blank','noopener');if(!w)return;const paras=f.content.value.trim().split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');w.document.write(`<title>${esc(f.title.value||'PPW Preview')}</title><style>body{max-width:820px;margin:40px auto;padding:24px;font:18px/1.75 Georgia;color:#222}h1{font:900 48px/1.05 Arial}img{max-width:100%}</style><h1>${esc(f.title.value||'Untitled')}</h1><p>By ${esc(f.author.value||'PPW Staff')} · ${esc(f.category.value||'')}</p><p>${esc(f.excerpt.value)}</p><hr>${paras}`);w.document.close()}
function filter(){const q=($("ppwArticleSearch")?.value||'').toLowerCase(),s=$("ppwStatusFilter")?.value||'all';document.querySelectorAll('.article-item').forEach(x=>{const t=x.textContent.toLowerCase(),b=x.querySelector('.badge')?.textContent.toLowerCase()||'';x.style.display=(!q||t.includes(q))&&(s==='all'||b===s||b.includes(s))?'':'none'})}
function stats(){const a=[...document.querySelectorAll('.article-item')],c={published:0,draft:0,scheduled:0};a.forEach(x=>{const s=(x.querySelector('.badge')?.textContent||'').toLowerCase();if(c[s]!=null)c[s]++});if($("ppwNewsroomStats"))$("ppwNewsroomStats").innerHTML=Object.entries(c).map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}
async function loadEdit(id){const {data,error}=await db.from('articles').select('*').eq('id',id).single();if(error)return;editingId=id;if($("ppwTags"))$("ppwTags").value=(data.tags||[]).join(', ');if($("ppwSchedule"))$("ppwSchedule").value=data.scheduled_at?new Date(data.scheduled_at).toISOString().slice(0,16):''}
function init(){addUI();restore();$("ppwPreview")?.addEventListener('click',preview);$("ppwArticleSearch")?.addEventListener('input',filter);$("ppwStatusFilter")?.addEventListener('change',filter);document.querySelector('#articleList')?.addEventListener('click',e=>{const b=e.target.closest('[data-action="edit"]');if(b)setTimeout(()=>loadEdit(Number(b.dataset.id)),250)},true);new MutationObserver(()=>{stats();filter()}).observe($("articleList"),{childList:true,subtree:true});form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(busy)return;busy=true;try{note('Saving article...');const status=await save('published');reset();$("refreshBtn")?.click();note(status==='scheduled'?'Story scheduled successfully.':'Article published successfully.','success')}catch(err){console.error(err);note(err.message||'Could not save article.','error')}finally{busy=false}},true);$("saveDraftBtn")?.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();if(busy)return;busy=true;try{note('Saving draft...');await save('draft');reset();$("refreshBtn")?.click();note('Draft saved successfully.','success')}catch(err){note(err.message||'Could not save draft.','error')}finally{busy=false}},true);setInterval(autosave,5000);setTimeout(()=>{stats();filter()},500)}
setTimeout(init,350);
})();