(()=>{
'use strict';
const U='https://qyipadinsphoyxotrceo.supabase.co',K='sb_publishable_S73dZKZ9ro03lWDbHFzZhw_5t5pDtGt',db=window.PPW_AUTH_DB||supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const loginView=$('loginView'),adminView=$('adminView'),loginForm=$('loginForm'),articleForm=$('articleForm'),articleList=$('articleList');let role=null,session=null,editing=null,busy=false;
const msg=(id,text,type='')=>{const e=$(id);if(e){e.textContent=text;e.className='message '+type}};
function setupFields(){const g=articleForm?.querySelector('.form-grid');if(!g)return;if(!$('ppwTags')){const a=document.createElement('label');a.className='full';a.innerHTML='Topics / Tags<input id="ppwTags" maxlength="250" placeholder="sports, student life, campus"><span class="help">Separate tags with commas.</span>';g.append(a)}if(!$('ppwSchedule')){const a=document.createElement('label');a.className='full';a.innerHTML='Schedule publication<input id="ppwSchedule" type="datetime-local"><span class="help">Leave blank for immediate publishing. Scheduled stories publish automatically.</span>';g.append(a)}}
async function getRole(s=session){if(!s?.user?.id)return null;const {data,error}=await db.from('admin_roles').select('role').eq('user_id',s.user.id).maybeSingle();if(error)throw error;return data?.role||null}
function renderArticles(data){const visible=(data||[]).filter(a=>role==='owner'||a.author_user_id===session?.user?.id);articleList.innerHTML=visible.length?visible.map(a=>`<article class="article-item"><div class="article-item-content"><div class="article-item-top"><div><h3>${esc(a.title)}</h3><p>${esc(a.category)} · ${esc(a.author)} · ${a.status==='scheduled'?`Publishes ${new Date(a.scheduled_at).toLocaleString()}`:new Date(a.published_at||a.created_at).toLocaleString()}</p></div><div class="badges"><span class="badge ${esc(a.status)}">${esc(a.status).toUpperCase()}</span>${a.featured?'<span class="badge published">LEAD</span>':''}</div></div><div class="article-actions"><button class="small-btn" data-action="edit" data-id="${a.id}">Edit</button>${a.status==='published'?`<a class="small-btn" target="_blank" href="../article.html?slug=${encodeURIComponent(a.slug)}">View</a>`:''}${role==='owner'?`<button class="small-btn danger" data-action="delete" data-id="${a.id}">Delete</button>`:''}</div></div></article>`).join(''):`<div class="empty-state">${role==='owner'?'No articles yet. Create your first story.':'You have not published any articles yet.'}</div>`}
async function load(){articleList.innerHTML='<div class="empty-state">Loading articles...</div>';try{const {data,error}=await db.from('articles').select('*').order('created_at',{ascending:false});if(error)throw error;renderArticles(data)}catch(e){console.error('PPW article query failed:',e);articleList.innerHTML=`<div class="empty-state">Could not load articles: ${esc(e.message||'Unknown error')}</div>`;msg('articleMessage',e.message||'Article list could not be loaded.','error')}}
async function activate(s,r){session=s;role=r;loginView.classList.add('hidden');adminView.classList.remove('hidden');if($('roleBadge'))$('roleBadge').innerHTML=`<span>${r==='owner'?'OWNER':'PUBLISHER'}</span><small>${esc(s.user.email||'')}</small>`;if($('permissionNotice'))$('permissionNotice').textContent=r==='owner'?'Owner access: full newsroom control.':'Publisher access: you can create articles and edit only your own articles.';setupFields();await load();window.dispatchEvent(new CustomEvent('ppw-admin-ready',{detail:{session:s,role:r}}))}
window.addEventListener('ppw-auth-sync',async e=>{const d=e.detail||{};if(!d.session?.user?.id||!d.role)return;try{await activate(d.session,d.role)}catch(x){console.error(x)}});
$('refreshBtn')?.addEventListener('click',load);
})();