(()=>{
'use strict';
const U='https://qyipadinsphoyxotrceo.supabase.co',K='sb_publishable_S73dZK9ro03lWDbHFzZhw_5t5pDtGt',db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const loginView=$('loginView'),adminView=$('adminView'),loginForm=$('loginForm'),articleForm=$('articleForm'),articleList=$('articleList');let role=null,session=null,editing=null,busy=false;
const msg=(id,text,type='')=>{const e=$(id);if(e){e.textContent=text;e.className='message '+type}};const slug=v=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,90);const localDate=v=>{if(!v)return '';const d=new Date(v),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)};
function setupFields(){const g=articleForm?.querySelector('.form-grid');if(!g)return;if(!$('ppwTags')){const a=document.createElement('label');a.className='full';a.innerHTML='Topics / Tags<input id="ppwTags" maxlength="250" placeholder="sports, student life, campus"><span class="help">Separate tags with commas.</span>';g.append(a)}if(!$('ppwSchedule')){const a=document.createElement('label');a.className='full';a.innerHTML='Schedule publication<input id="ppwSchedule" type="datetime-local"><span class="help">Leave blank for immediate publishing. Scheduled stories publish automatically.</span>';g.append(a)}if(!$('ppwEditorTools')){const x=document.createElement('div');x.id='ppwEditorTools';x.className='ppw-admin-tools';x.innerHTML='<button id="ppwPreview" class="secondary-btn" type="button">Preview</button><span>Autosave is on</span>';articleForm.querySelector('.form-actions')?.before(x);$('ppwPreview').onclick=preview}}
function tags(){return String($('ppwTags')?.value||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).slice(0,12)}
function reset(){articleForm.reset();editing=null;$('articleId').value='';$('author').value='PPW Staff';$('publishNow').checked=true;$('editorHeading').textContent='Create Article';$('cancelEditBtn').classList.add('hidden');$('currentImageWrap').classList.add('hidden');$('currentGalleryWrap').classList.add('hidden');$('currentGallery').innerHTML='';$('imagePreviewGrid').innerHTML='';if($('ppwTags'))$('ppwTags').value='';if($('ppwSchedule'))$('ppwSchedule').value='';msg('articleMessage','')}
async function getRole(){if(!session?.user?.id)return null;const {data,error}=await db.from('admin_roles').select('role').eq('user_id',session.user.id).maybeSingle();if(error)throw error;return data?.role||null}
async function show(s){session=s||null;role=null;if(!s){loginView.classList.remove('hidden');adminView.classList.add('hidden');return}try{role=await getRole()}catch(e){msg('loginMessage','Could not verify your newsroom role. Please sign in again.','error');await db.auth.signOut();return}if(!role){msg('loginMessage','This account is not assigned to the PPW newsroom.','error');await db.auth.signOut();return}loginView.classList.add('hidden');adminView.classList.remove('hidden');$('roleBadge').innerHTML=`<span>${role==='owner'?'OWNER':'PUBLISHER'}</span><small>${esc(s.user.email||'')}</small>`;$('permissionNotice').textContent=role==='owner'?'Owner access: full newsroom control.':'Publisher access: articles only.';setupFields();await load()}
async function check(){const {data}=await db.auth.getSession();await show(data.session)}
loginForm?.addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;msg('loginMessage','Signing in...');const {data,error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim().toLowerCase(),password:$('loginPassword').value});if(error)msg('loginMessage',error.message,'error');else{loginForm.reset();await show(data.session)}b.disabled=false});$('logoutBtn')?.addEventListener('click',async()=>{await db.auth.signOut();reset();show(null)});$('cancelEditBtn')?.addEventListener('click',reset);$('refreshBtn')?.addEventListener('click',load);
$('imageFile')?.addEventListener('change',()=>{const files=[...$('imageFile').files];$('imagePreviewGrid').innerHTML=files.map((f,i)=>`<div class="image-preview-card"><img src="${URL.createObjectURL(f)}" alt="Selected photo ${i+1}"><span>${i?'Gallery photo '+(i+1):'Cover photo'}</span></div>`).join('');if(files.length)msg('articleMessage',`${files.length} photo${files.length===1?'':'s'} selected. The first is the cover.`)});
async function upload(file){if(file.size>6*1024*1024)throw Error(`${file.name} is larger than 6 MB.`);if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error(`${file.name} is not a supported image type.`);const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`articles/${crypto.randomUUID?.()||Date.now()+Math.random().toString(36).slice(2)}.${['jpg','jpeg','png','webp','gif'].includes(ext)?ext:'jpg'}`,r=await db.storage.from('article-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(r.error)throw Error(r.error.message);return db.storage.from('article-images').getPublicUrl(r.data.path).data.publicUrl}
async function gallery(id){const r=await db.from('article_images').select('*').eq('article_id',id).order('sort_order');if(r.error)throw r.error;return r.data||[]}
async function save(status){if(busy)return;busy=true;try{const title=$('title').value.trim(),body=$('content').value.trim();if(!title||!body)throw Error('Please enter both a headline and the article text.');const raw=$('ppwSchedule')?.value||'',schedule=raw?new Date(raw):null;if(schedule&&schedule<=new Date())throw Error('Scheduled publication must be in the future.');const files=[...$('imageFile').files];let image=editing?.image_url||null;if(files[0])image=await upload(files[0]);const actual=schedule?'scheduled':status,data={title,slug:editing&&editing.title===title?editing.slug:slug(title),excerpt:$('excerpt').value.trim(),content:body,category:$('category').value,author:$('author').value.trim()||'PPW Staff',image_url:image,published_at:actual==='published'?($('publishedAt').value?new Date($('publishedAt').value).toISOString():new Date().toISOString()):null,scheduled_at:actual==='scheduled'?schedule.toISOString():null,status:actual,tags:tags(),updated_at:new Date().toISOString()};const r=editing?await db.from('articles').update(data).eq('id',editing.id):await db.from('articles').insert(data).select('id').single();if(r.error)throw r.error;const id=editing?editing.id:r.data.id;if(files.length>1){const old=await gallery(id),rows=[];for(let i=1;i<files.length;i++)rows.push({article_id:id,image_url:await upload(files[i]),sort_order:old.length+i-1,alt_text:title});const gr=await db.from('article_images').insert(rows);if(gr.error)throw gr.error}if(actual==='published'){await db.from('articles').update({featured:false}).neq('id',id);await db.from('articles').update({featured:true}).eq('id',id)}localStorage.removeItem('ppw-admin-draft-v3');return actual}finally{busy=false}}
articleForm?.addEventListener('submit',async e=>{e.preventDefault();try{msg('articleMessage','Saving...');const s=await save('published');reset();await load();msg('articleMessage',s==='scheduled'?'Story scheduled successfully.':'Article published successfully.','success')}catch(x){console.error(x);msg('articleMessage',x.message||'Could not save article.','error')}});$('saveDraftBtn')?.addEventListener('click',async()=>{try{msg('articleMessage','Saving draft...');await save('draft');reset();await load();msg('articleMessage','Draft saved successfully.','success')}catch(x){msg('articleMessage',x.message||'Could not save draft.','error')}});
async function load(){articleList.innerHTML='<div class="empty-state">Loading articles...</div>';const {data,error}=await db.from('articles').select('*').order('created_at',{ascending:false});if(error){articleList.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`;return}articleList.innerHTML=data?.length?data.map(a=>`<article class="article-item"><div class="article-item-content"><div class="article-item-top"><div><h3>${esc(a.title)}</h3><p>${esc(a.category)} · ${esc(a.author)} · ${a.status==='scheduled'?`Publishes ${new Date(a.scheduled_at).toLocaleString()}`:new Date(a.published_at||a.created_at).toLocaleString()}</p></div><div class="badges"><span class="badge ${esc(a.status)}">${esc(a.status).toUpperCase()}</span>${a.featured?'<span class="badge published">LEAD</span>':''}</div></div><div class="article-actions"><button class="small-btn" data-action="edit" data-id="${a.id}">Edit</button>${a.status==='published'?`<a class="small-btn" target="_blank" href="../article.html?slug=${encodeURIComponent(a.slug)}">View</a>`:''}${role==='owner'?`<button class="small-btn danger" data-action="delete" data-id="${a.id}">Delete</button>`:''}</div></div></article>`).join(''):'<div class="empty-state">No articles yet. Create your first story.</div>'}
articleList?.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=Number(b.dataset.id);if(b.dataset.action==='edit')edit(id);if(b.dataset.action==='delete'&&role==='owner'&&confirm('Delete this article?')){const r=await db.from('articles').delete().eq('id',id);if(r.error)msg('articleMessage',r.error.message,'error');else load()}});
async function edit(id){const r=await db.from('articles').select('*').eq('id',id).single();if(r.error)return msg('articleMessage',r.error.message,'error');editing=r.data;$('articleId').value=r.data.id;$('title').value=r.data.title||'';$('category').value=r.data.category||'School News';$('author').value=r.data.author||'PPW Staff';$('excerpt').value=r.data.excerpt||'';$('content').value=r.data.content||'';$('publishedAt').value=localDate(r.data.published_at);if($('ppwTags'))$('ppwTags').value=(r.data.tags||[]).join(', ');if($('ppwSchedule'))$('ppwSchedule').value=localDate(r.data.scheduled_at);$('editorHeading').textContent='Edit Article';$('cancelEditBtn').classList.remove('hidden');if(r.data.image_url){$('currentImage').src=r.data.image_url;$('currentImageWrap').classList.remove('hidden')}const g=await gallery(id);$('currentGallery').innerHTML=g.map((x,i)=>`<div class="image-preview-card"><img src="${esc(x.image_url)}" alt="${esc(x.alt_text||r.data.title)}"><span>Gallery photo ${i+1}</span><button type="button" class="small-btn danger" data-gallery-delete="${x.id}">Remove</button></div>`).join('');$('currentGalleryWrap').classList.toggle('hidden',!g.length);window.scrollTo({top:0,behavior:'smooth'})}
$('currentGallery')?.addEventListener('click',async e=>{const b=e.target.closest('[data-gallery-delete]');if(!b||!editing)return;if(!confirm('Remove this gallery photo?'))return;const r=await db.from('article_images').delete().eq('id',Number(b.dataset.galleryDelete));if(r.error)msg('articleMessage',r.error.message,'error');else edit(editing.id)});
function preview(){const w=open('','_blank','noopener');if(!w)return;w.document.write(`<title>${esc($('title').value||'PPW Preview')}</title><style>body{max-width:850px;margin:40px auto;padding:24px;font:18px/1.75 Georgia;color:#222}h1{font:900 46px Arial}</style><h1>${esc($('title').value||'Untitled')}</h1><p>By ${esc($('author').value||'PPW Staff')}</p><p>${esc($('excerpt').value)}</p><hr><div>${esc($('content').value).replace(/\n/g,'<br>')}</div>`);w.document.close()}
function autosave(){if(editing)return;const d={title:$('title').value,category:$('category').value,author:$('author').value,excerpt:$('excerpt').value,content:$('content').value,tags:$('ppwTags')?.value||'',schedule:$('ppwSchedule')?.value||'',savedAt:Date.now()};if(d.title||d.content)localStorage.setItem('ppw-admin-draft-v3',JSON.stringify(d))}function restore(){try{const d=JSON.parse(localStorage.getItem('ppw-admin-draft-v3')||'null');if(!d||Date.now()-d.savedAt>604800000)return;$('title').value=d.title||'';$('category').value=d.category||'School News';$('author').value=d.author||'PPW Staff';$('excerpt').value=d.excerpt||'';$('content').value=d.content||'';if($('ppwTags'))$('ppwTags').value=d.tags||'';if($('ppwSchedule'))$('ppwSchedule').value=d.schedule||'';msg('articleMessage','Recovered an unsaved local draft.','success')}catch{}}
setupFields();setInterval(autosave,5000);setTimeout(restore,500);check();
})();