-- Run this AFTER the existing PPW Supabase setup.
-- This adds support for multiple photos inside one article.

create table if not exists public.article_images (
    id bigint generated by default as identity primary key,
    article_id bigint not null references public.articles(id) on delete cascade,
    image_url text not null,
    sort_order integer not null default 0,
    alt_text text,
    created_at timestamptz not null default now()
);

alter table public.article_images enable row level security;

drop policy if exists "PPW public can view article gallery" on public.article_images;
drop policy if exists "PPW admins can add article gallery images" on public.article_images;
drop policy if exists "PPW admins can update article gallery images" on public.article_images;
drop policy if exists "PPW admins can delete article gallery images" on public.article_images;

create policy "PPW public can view article gallery"
on public.article_images for select
to anon, authenticated
using (true);

create policy "PPW admins can add article gallery images"
on public.article_images for insert
to authenticated
with check (true);

create policy "PPW admins can update article gallery images"
on public.article_images for update
to authenticated
using (true)
with check (true);

create policy "PPW admins can delete article gallery images"
on public.article_images for delete
to authenticated
using (true);
