(()=>{
const WORDS=["APPLE","BEACH","BRAIN","BRAVE","CAMPUS","CANDY","CHAIR","CLASS","CLOUD","DANCE","DREAM","EAGLE","EARTH","FIELD","FLAME","FRESH","FRUIT","GIANT","GRAPE","GREEN","HAPPY","HEART","HOUSE","LIGHT","MANGO","MUSIC","NORTH","OCEAN","PAPER","PEACE","PHONE","PIANO","PLANT","PRIDE","QUICK","RADIO","RIVER","ROBOT","SCHOOL","SHARE","SMILE","SPORT","STORY","STUDY","TIGER","TODAY","TRAIN","TRAIL","TRUST","VOICE","WATER","WORLD","WRITE","YOUTH"];
const valid=new Set(WORDS),day=Math.floor((Date.now()-Date.UTC(2026,0,1))/86400000),answer=WORDS[((day%WORDS.length)+WORDS.length)%WORDS.length];
const today=new Date().toISOString().slice(0,10),key=`ppw-pawword-${today}`,board=document.getElementById("wordBoard"),msg=document.getElementById("wordMessage"),keyboard=document.getElementById("keyboard"),reset=document.getElementById("wordReset"),date=document.getElementById("wordDate");
const statKey="ppw-game-stats-v2";
let stats=JSON.parse(localStorage.getItem(statKey)||'{"played":0,"streak":0,"lastDay":"","bestMemory":null,"weekDays":[]}');
function saveStats(){localStorage.setItem(statKey,JSON.stringify(stats));renderStats()}
function markPlayed(){const d=new Date();const keyDay=Math.floor((d-Date.UTC(d.getFullYear(),0,1))/86400000);if(stats.lastDay!==today){stats.played++;if(stats.lastDay){const prev=new Date(stats.lastDay);prev.setDate(prev.getDate()+1);stats.streak=prev.toISOString().slice(0,10)===today?stats.streak+1:1}else stats.streak=1;stats.lastDay=today;stats.weekDays=Array.isArray(stats.weekDays)?stats.weekDays:[];if(!stats.weekDays.includes(today))stats.weekDays.push(today);stats.weekDays=stats.weekDays.filter(x=>{const dt=new Date(x);return (d-dt)/86400000<7});saveStats()} }
function renderStats(){const a=document.getElementById("gamesStreak"),b=document.getElementById("gamesPlayed"),c=document.getElementById("gamesBest"),d=document.getElementById("challengeDays");if(a)a.textContent=stats.streak||0;if(b)b.textContent=stats.played||0;if(c)c.textContent=stats.bestMemory?`${(stats.bestMemory/1000).toFixed(1)}s`:"—";if(d)d.textContent=(stats.weekDays||[]).length}
renderStats();

if(board){let guesses=JSON.parse(localStorage.getItem(key)||"[]"),finished=localStorage.getItem(key+"-finished")==="1",current="";date.textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"}).toUpperCase();
function buildBoard(){board.innerHTML="";for(let r=0;r<6;r++)for(let c=0;c<5;c++){let x=document.createElement("div");x.className="word-cell";x.dataset.row=r;x.dataset.col=c;board.appendChild(x)}}
const keyRows=["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"],keys={};
function buildKeys(){keyboard.innerHTML="";keyRows.forEach((letters,i)=>{let row=document.createElement("div");row.className="key-row";if(i===2){let b=document.createElement("button");b.className="key wide";b.textContent="ENTER";b.onclick=submit;row.appendChild(b)}[...letters].forEach(l=>{let b=document.createElement("button");b.className="key";b.textContent=l;b.onclick=()=>add(l);keys[l]=b;row.appendChild(b)});if(i===2){let b=document.createElement("button");b.className="key wide";b.textContent="⌫";b.onclick=back;row.appendChild(b)}keyboard.appendChild(row)})}
function paint(){guesses.forEach((g,r)=>[...g].forEach((l,c)=>{let x=board.querySelector(`[data-row="${r}"][data-col="${c}"]`);x.textContent=l;x.classList.add("filled",l===answer[c]?"correct":answer.includes(l)?"present":"absent")}));if(current&&!finished)[...current].forEach((l,c)=>{let x=board.querySelector(`[data-row="${guesses.length}"][data-col="${c}"]`);x.textContent=l;x.classList.add("filled","pop")})}
function say(t,c=""){msg.textContent=t;msg.className=`game-message ${c}`}
function add(l){if(!finished&&current.length<5){current+=l;paint()}}function back(){if(!finished){current=current.slice(0,-1);paint()}}
function updateKeys(){[...new Set(guesses.flatMap(g=>[...g]))].forEach(l=>{let b=keys[l];if(!b)return;let good=guesses.some(g=>[...g].some((x,i)=>x===l&&answer[i]===l));b.className=`key ${good?"correct":answer.includes(l)?"present":"absent"}`})}
function submit(){if(finished)return;if(current.length<5)return say("You need five letters.","error");if(!valid.has(current))return say("That word isn't in today's list.","error");guesses.push(current);localStorage.setItem(key,JSON.stringify(guesses));markPlayed();if(current===answer){finished=true;localStorage.setItem(key+"-finished","1");say(`You got it in ${guesses.length} ${guesses.length===1?"guess":"guesses"}! Come back tomorrow.","win");reset.classList.remove("hidden")}else if(guesses.length===6){finished=true;localStorage.setItem(key+"-finished","1");say(`Today's word was ${answer}. Come back tomorrow!`);reset.classList.remove("hidden")}else say(`${6-guesses.length} guesses left.`);current="";paint();updateKeys()}
document.addEventListener("keydown",e=>{if(/^[a-z]$/i.test(e.key))add(e.key.toUpperCase());else if(e.key==="Backspace")back();else if(e.key==="Enter")submit()});reset.onclick=()=>{guesses=[];finished=false;current="";localStorage.removeItem(key);localStorage.removeItem(key+"-finished");reset.classList.add("hidden");say("Type a five-letter word.");buildBoard();buildKeys();paint()};buildBoard();buildKeys();paint();updateKeys();if(finished)say(guesses.at(-1)===answer?`You already solved today's PawWord in ${guesses.length} guesses.`:`Today's word was ${answer}. Come back tomorrow!`,guesses.at(-1)===answer?"win":"")}

const puzzle=["TIGER","ROBOT","#####","APPLE","RADIO"],cw=document.getElementById("crosswordGrid"),ac=document.getElementById("acrossClues"),dc=document.getElementById("downClues"),check=document.getElementById("checkCrossword"),clear=document.getElementById("clearCrossword"),cm=document.getElementById("crosswordMessage");
if(cw){const inputs=[];puzzle.forEach((row,r)=>[...row].forEach((ch,c)=>{let cell=document.createElement("div");cell.className="cw-cell";if(ch==="#")cell.classList.add("block");else{let n=document.createElement("span");n.className="cw-number";n.textContent=r*5+c+1;cell.appendChild(n);let i=document.createElement("input");i.className="cw-input";i.maxLength=1;i.dataset.answer=ch;i.autocomplete="off";i.addEventListener("input",()=>{i.value=i.value.replace(/[^a-z]/gi,"").toUpperCase();if(i.value)inputs[inputs.indexOf(i)+1]?.focus()});i.addEventListener("keydown",e=>{if(e.key==="Backspace"&&!i.value)inputs[inputs.indexOf(i)-1]?.focus()});cell.appendChild(i);inputs.push(i)}cw.appendChild(cell)}));
["Wilson's school mascot","A machine that can be programmed","A crunchy fruit","Something you might listen to"].forEach(x=>{let li=document.createElement("li");li.textContent=x;ac.appendChild(li)});["Animal with stripes","A machine helper","A fruit often used in pie","Something that sends sound"].forEach(x=>{let li=document.createElement("li");li.textContent=x;dc.appendChild(li)});
check.onclick=()=>{let ok=true,n=0;inputs.forEach(i=>{i.classList.remove("correct","wrong");if(i.value===i.dataset.answer){i.classList.add("correct");n++}else{ok=false;if(i.value)i.classList.add("wrong")}});markPlayed();cm.textContent=ok?"Nice! You solved the mini crossword.":`${n} of ${inputs.length} squares are correct.`;cm.className=`game-message ${ok?"win":""}`};clear.onclick=()=>{inputs.forEach(i=>{i.value="";i.classList.remove("correct","wrong")});cm.textContent="Fill the grid, then check your answers.";cm.className="game-message";inputs[0]?.focus()}}

const memory=document.getElementById("memoryGrid");
if(memory){const symbols=["🐯","★","✦","●","◆","▲","✿","☀"],cards=[...symbols,...symbols].sort(()=>Math.random()-.5);let open=[],matched=0,moves=0,locked=false,start=0;const moveEl=document.getElementById("memoryMoves"),message=document.getElementById("memoryMessage");function setup(){memory.innerHTML="";open=[];matched=0;moves=0;locked=false;start=performance.now();moveEl.textContent="0";message.textContent="Find all eight pairs.";cards.sort(()=>Math.random()-.5);cards.forEach((s,i)=>{const b=document.createElement("button");b.className="memory-card";b.setAttribute("aria-label","Hidden memory card");b.innerHTML=`<span class="memory-back">?</span><span class="memory-face">${s}</span>`;b.onclick=()=>flip(b,i,s);memory.appendChild(b)})}function flip(b,i,s){if(locked||b.classList.contains("flipped")||b.classList.contains("matched"))return;b.classList.add("flipped");open.push({b,i,s});if(open.length<2)return;moves++;moveEl.textContent=moves;if(open[0].s===open[1].s){open.forEach(x=>x.b.classList.add("matched"));matched+=2;open=[];if(matched===cards.length){const time=performance.now()-start;if(!stats.bestMemory||time<stats.bestMemory)stats.bestMemory=time;markPlayed();saveStats();message.textContent=`You matched them all in ${moves} moves and ${(time/1000).toFixed(1)} seconds!`;message.className="game-message win"}}else{locked=true;setTimeout(()=>{open.forEach(x=>x.b.classList.remove("flipped"));open=[];locked=false},650)}}document.getElementById("memoryRestart").onclick=setup;setup()}
})();
