(()=>{
'use strict';
const U='https://qyipadinsphoyxotrceo.supabase.co',K='sb_publishable_S73dZK9ro03lWDbHFzZhw_5t5pDtGt';
const db=window.supabase?.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const key=()=>{let k=localStorage.getItem('ppw-visitor-key');if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('ppw-visitor-key',k)}return k};
const css=href=>{if(!document.querySelector(`link[href^="${href.split('?')[0]}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}};css((location.pathname.includes('/admin/')?'../':'')+'ppw-v2.css?v=3');
function injectAnnouncement(){if(!db||document.querySelector('.ppw-announcement'))return;db.from('ppw_announcements').select('message,link').eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>{if(!data)return;const b=document.createElement('div');b.className='ppw-announcement';b.innerHTML=`<span>${esc(data.message||'')}</span>${data.link?`<a href="${esc(data.link)}">Read more →</a>`:''}<button type="button" aria-label="Close announcement">×</button>`;document.body.prepend(b);b.querySelector('button').onclick=()=>b.remove()}).catch(()=>{})}
function injectSearch(){const host=document.querySelector('#latest .section-head');if(!host||document.querySelector('#ppwSearch'))return;const box=document.createElement('div');box.className='ppw-search-box';box.innerHTML='<label for="ppwSearch">Search PPW</label><input id="ppwSearch" type="search" placeholder="Search stories, authors, tags..." aria-label="Search PPW"><div id="ppwSearchResults" class="ppw-search-results"></div>';host.appendChild(box);const input=box.querySelector('input'),results=box.querySelector('#ppwSearchResults');let timer;input.addEventListener('input',()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){results.innerHTML='';return}timer=setTimeout(async()=>{const {data}=await db.from('articles').select('title,slug,excerpt,author,category,tags,published_at').eq('status','published').order('published_at',{ascending:false}).limit(50);const rows=(data||[]).filter(a=>`${a.title} ${a.excerpt||''} ${a.author||''} ${a.category||''} ${(a.tags||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase())).slice(0,8);results.innerHTML=rows.length?rows.map(a=>`<a href="article.html?slug=${encodeURIComponent(a.slug)}"><strong>${esc(a.title)}</strong><small>${esc(a.category)} · ${esc(a.author||'PPW Staff')}</small></a>`).join(''):'<p>No stories matched that search.</p>'},120)})}
function injectMostRead(){if(!db||document.querySelector('#mostRead'))return;const anchor=document.querySelector('.staff-section');if(!anchor)return;const sec=document.createElement('section');sec.id='mostRead';sec.className='section ppw-extra-section';sec.innerHTML='<div class="section-head"><div><span class="eyebrow">READERS ARE READING</span><h2>Most Read</h2></div></div><div class="ppw-list-grid" id="mostReadList"><div class="loading-card">Loading...</div></div>';anchor.before(sec);Promise.all([db.from('ppw_article_views').select('article_id').limit(1000),db.from('articles').select('id,title,slug,category,published_at').eq('status','published').order('published_at',{ascending:false}).limit(100)]).then(([v,a])=>{const counts={};(v.data||[]).forEach(x=>counts[x.article_id]=(counts[x.article_id]||0)+1);const rows=(a.data||[]).sort((x,y)=>(counts[y.id]||0)-(counts[x.id]||0)).slice(0,5);document.querySelector('#mostReadList').innerHTML=rows.length?rows.map((x,i)=>`<a class="ppw-list-card" href="article.html?slug=${encodeURIComponent(x.slug)}"><span>${i+1}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.category)} · ${counts[x.id]||0} reads</small></div></a>`).join(''):'<p>No reading data yet.</p>'}).catch(()=>{})}
function injectPoll(){if(!db||document.querySelector('#ppwPoll'))return;const anchor=document.querySelector('.about-section');if(!anchor)return;const sec=document.createElement('section');sec.id='ppwPoll';sec.className='section ppw-extra-section';sec.innerHTML='<div class="section-head"><div><span class="eyebrow">WILSON VOICES</span><h2>Poll</h2></div></div><div class="ppw-poll-card" id="pollCard">Loading poll...</div>';anchor.before(sec);db.from('ppw_polls').select('*').eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle().then(async({data})=>{const card=document.querySelector('#pollCard');if(!data){card.innerHTML='<p>No active poll right now.</p>';return}const opts=Array.isArray(data.options)?data.options:[];const {data:votes}=await db.from('ppw_poll_votes').select('option_index').eq('poll_id',data.id);const counts=opts.map((_,i)=>(votes||[]).filter(v=>v.option_index===i).length);const voted=localStorage.getItem(`ppw-poll-${data.id}`)==='1';card.innerHTML=`<h3>${esc(data.question)}</h3><div class="poll-options">${opts.map((o,i)=>`<button type="button" data-poll-index="${i}" ${voted?'disabled':''}><span>${esc(o)}</span><b>${counts[i]}</b></button>`).join('')}</div><p class="poll-note">${voted?'Thanks for voting!':'One vote per device.'}</p>`;card.querySelectorAll('[data-poll-index]').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.pollIndex);const r=await db.from('ppw_poll_votes').insert({poll_id:data.id,option_index:i,visitor_key:key()});if(r.error){card.querySelector('.poll-note').textContent='You already voted on this device.';return}localStorage.setItem(`ppw-poll-${data.id}`,'1');b.disabled=true;card.querySelector('.poll-note').textContent='Thanks for voting!'} )}).catch(()=>{})}
function injectArchive(){if(!db||document.querySelector('#ppwArchive'))return;const more=document.querySelector('.more-sections');if(!more)return;const sec=document.createElement('section');sec.id='ppwArchive';sec.className='section ppw-extra-section';sec.innerHTML='<div class="section-head"><div><span class="eyebrow">THE ARCHIVE</span><h2>Past Issues</h2></div></div><div class="ppw-list-grid" id="issueList"><div class="loading-card">Loading issues...</div></div>';more.after(sec);db.from('ppw_issues').select('issue_name,issue_date,description,issue_url').order('issue_date',{ascending:false}).limit(12).then(({data})=>{document.querySelector('#issueList').innerHTML=(data||[]).length?(data||[]).map(i=>`<a class="ppw-list-card" href="${esc(i.issue_url||'#')}"><span>ISSUE</span><div><strong>${esc(i.issue_name||'PPW Issue')}</strong><small>${esc(i.issue_date||'')} ${i.description?`· ${esc(i.description)}`:''}</small></div></a>`).join(''):'<p>No past issues have been added yet.</p>'}).catch(()=>{})}
function injectWeekly(){if(document.querySelector('#ppwWeek'))return;const nav=document.querySelector('.welcome-strip');if(!nav)return;const d=new Date(),card=document.createElement('div');card.id='ppwWeek';card.className='ppw-week-strip';card.innerHTML=`<strong>THIS WEEK AT WILSON</strong><span>${d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</span><a href="#latest">Explore PPW →</a>`;nav.after(card)}
function injectHomepage(){injectAnnouncement();injectSearch();injectMostRead();injectPoll();injectArchive();injectWeekly()}
function articleExtras(){if(!document.querySelector('#articleContent'))return;const content=document.querySelector('.article-body');if(content&&!document.querySelector('.ppw-reading-time')){const words=(content.textContent||'').trim().split(/\s+/).filter(Boolean).length,p=document.createElement('div');p.className='ppw-reading-time';p.textContent=`${Math.max(1,Math.ceil(words/220))} min read`;content.before(p)}}
function adminExtras(){if(location.pathname.includes('/admin/'))document.body.classList.add('ppw-admin-v2')}
function loadFinal(){if(document.getElementById('ppwFinalScript'))return;const s=document.createElement('script');s.id='ppwFinalScript';s.src=(location.pathname.includes('/admin/')?'../':'')+'ppw-final.js?v=2';document.body.appendChild(s)}
function boot(){loadFinal();if(location.pathname.includes('/admin/'))adminExtras();else if(location.pathname.endsWith('article.html'))articleExtras();else injectHomepage()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,350));else setTimeout(boot,350);
})();