(()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='ppw-fixes.css?v=14';document.head.appendChild(l);const i=document.createElement('link');i.rel='stylesheet';i.href='ppw-interactive.css?v=8';document.head.appendChild(i);const a=document.createElement('link');a.rel='stylesheet';a.href='ppw-animation-fix.css?v=14';document.head.appendChild(a);const h=document.createElement('link');h.rel='stylesheet';h.href='homepage-loader.css?v=1';document.head.appendChild(h)})();
'use strict';
const SUPABASE_URL='https://qyipadinsphoyxotrceo.supabase.co';
const SUPABASE_KEY='sb_publishable_S73dZKZ9ro03lWDbHFzZhw_5t5pDtGt';
const db=window.supabase?.createClient?.(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const date=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}).toUpperCase()};
const href=a=>`article.html?slug=${encodeURIComponent(a.slug||'')}`;
const img=(a,cls='story-image')=>a.image_url?`<img class="${cls}" src="${esc(a.image_url)}" alt="${esc(a.title||'')}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling&&(this.nextElementSibling.style.display='grid')"><div class="story-placeholder fallback-placeholder" style="display:none">${esc(a.category||'PPW').toUpperCase()}</div>`:`<div class="story-placeholder">${esc(a.category||'PPW').toUpperCase()}</div>`;
const card=a=>`<article class="story-card reveal"><a href="${href(a)}">${img(a)}<div class="story-body"><span class="category-pill">${esc(a.category||'PPW').toUpperCase()}</span><h3>${esc(a.title||'Untitled Article')}</h3><p>${esc(a.excerpt||'Read the latest story from Paw Prints Weekly.')}</p><div class="meta"><span>${esc((a.author||'PPW Staff').toUpperCase())}</span><span>${date(a.published_at)}</span></div></div></a></article>`;
function setupNav(){const toggle=document.getElementById('menuToggle'),nav=document.getElementById('mainNav');if(!nav)return;if(!nav.querySelector('a[href="games.html"]')){const games=document.createElement('a');games.href='games.html';games.textContent='Games';const more=[...nav.querySelectorAll('a')].find(a=>a.textContent.trim().toLowerCase()==='more');more?more.after(games):nav.appendChild(games)}toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.classList.remove('active');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));const current=document.getElementById('currentDate');if(current)current.textContent=new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'}).toUpperCase()}
let revealObserver;function revealSetup(){const items=document.querySelectorAll('.reveal');if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){items.forEach(e=>e.classList.add('visible'));return}revealObserver ||= new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.08,rootMargin:'0px 0px -30px 0px'});items.forEach(e=>{if(!e.dataset.ppwObserved){e.dataset.ppwObserved='1';revealObserver.observe(e)}})}
function renderFeatured(articles){const el=document.getElementById('featuredArticle');if(!el)return;const chosen=[...articles.filter(a=>a.featured===true),...articles.filter(a=>a.featured!==true)].slice(0,2);if(!chosen.length){el.innerHTML='<div class="empty-card">No featured stories yet.</div>';return}el.classList.add('dual-featured');el.innerHTML=chosen.map((a,i)=>`<article class="featured-card reveal"><a href="${href(a)}">${img(a)}<div class="story-body"><div class="featured-badge">${i?'ALSO FEATURED':"EDITOR'S LEAD"}</div><span class="category-pill">${esc(a.category||'PPW').toUpperCase()}</span><h3>${esc(a.title||'Untitled Article')}</h3><p>${esc(a.excerpt||'Read this story from Paw Prints Weekly.')}</p><div class="meta"><span>${esc((a.author||'PPW Staff').toUpperCase())}</span><span>${date(a.published_at)}</span></div></div></a></article>`).join('')}
const categoryIds={'School News':'cat-school-news','Student Life':'cat-student-life','Sports':'cat-sports','Perspectives':'cat-perspectives','World Events':'cat-world-events','Features':'cat-features','Entertainment & Media':'cat-entertainment-media','Editorial':'cat-editorial'};
const normalizeCategory=v=>String(v??'').replace(/\s+/g,' ').trim().toLowerCase();
function renderCategories(articles,error=false){Object.entries(categoryIds).forEach(([cat,id])=>{const el=document.getElementById(id);if(!el)return;if(error){el.innerHTML='<div class="empty-card error-card">This section could not load right now. Please refresh the page.</div>';return}const key=normalizeCategory(cat);const rows=articles.filter(a=>normalizeCategory(a.category)===key).slice(0,6);el.innerHTML=rows.length?rows.map(card).join(''):`<div class="empty-card">No ${esc(cat.toLowerCase())} stories have been published yet.</div>`})}
async function publicTable(table,select,filter=''){const url=`${SUPABASE_URL}/rest/v1/${table}?select=${encodeURIComponent(select)}${filter}`;const r=await fetch(url,{method:'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,Accept:'application/json','Content-Type':'application/json'}});if(!r.ok){const text=await r.text();throw new Error(`REST ${table} ${r.status}: ${text.slice(0,240)}`)}return r.json()}
async function getPublishedArticles(){const select='id,title,slug,excerpt,category,author,image_url,published_at,featured,status';let lastError=null;try{const rows=await publicTable('articles',select,'&status=eq.published&order=published_at.desc');if(Array.isArray(rows))return rows}catch(e){lastError=e;console.warn('PPW REST filtered article request failed:',e)}try{const rows=await publicTable('articles',select,'&order=published_at.desc');if(Array.isArray(rows))return rows.filter(a=>String(a.status||'').toLowerCase()==='published')}catch(e){lastError=e;console.warn('PPW REST unfiltered article request failed:',e)}try{if(!db)throw new Error('Supabase client unavailable');const r=await db.from('articles').select(select).eq('status','published').order('published_at',{ascending:false});if(!r.error&&Array.isArray(r.data))return r.data;lastError=r.error||new Error('No article data returned')}catch(e){lastError=e;console.warn('PPW client article request failed:',e)}throw lastError||new Error('Unable to load published articles')}
async function loadArticles(){const latest=document.getElementById('latestArticles'),featured=document.getElementById('featuredArticle');if(latest)latest.innerHTML='<div class="loading-card">Loading articles...</div>';renderCategories([],false);try{const articles=await getPublishedArticles();console.info('PPW loaded published articles:',articles.length);if(latest)latest.innerHTML=articles.length?articles.slice(0,6).map(card).join(''):'<div class="empty-card">No published stories yet.</div>';renderFeatured(articles);renderCategories(articles);revealSetup()}catch(e){console.error('PPW article load failed:',e);if(latest)latest.innerHTML='<div class="empty-card error-card">The newsroom is temporarily unavailable. Please refresh the page.</div>';if(featured)featured.innerHTML='<div class="empty-card error-card">Featured stories could not be loaded.</div>';renderCategories([],true)}}
async function loadStaff(){const el=document.getElementById('staffGrid');if(!el)return;el.innerHTML='<div class="loading-card">Loading staff...</div>';try{let data=[];try{if(!db)throw new Error('Supabase client unavailable');let result=await db.from('staff_members').select('name,role,bio,sort_order').eq('active',true).order('sort_order',{ascending:true});if(result.error)throw result.error;data=result.data||[]}catch(e){console.warn('PPW client staff query failed; using REST:',e);data=await publicTable('staff_members','name,role,bio,sort_order','&active=eq.true&order=sort_order.asc')}if(!data.length){el.innerHTML='<div class="empty-card">Staff information will appear here soon.</div>';return}el.innerHTML=data.map(m=>`<article class="staff-card reveal"><div class="staff-initial">${esc((m.name||'P').trim().charAt(0).toUpperCase())}</div><div><span class="staff-role">${esc(m.role||'Staff Member')}</span><h3>${esc(m.name||'PPW Staff')}</h3>${m.bio?`<p>${esc(m.bio)}</p>`:''}</div></article>`).join('');revealSetup()}catch(e){console.error('PPW staff load failed:',e);el.innerHTML='<div class="empty-card error-card">Staff information is temporarily unavailable.</div>'}}
function favicon(){if(!document.querySelector('link[rel="icon"]')){const x=document.createElement('link');x.rel='icon';x.type='image/png';x.href='images/tiger.png';document.head.appendChild(x)}}
function finishLoader(){const loader=document.getElementById('ppwLoader');document.body.classList.remove('ppw-loading');document.documentElement.classList.remove('ppw-loader-active');document.body.classList.add('ppw-intro-done');requestAnimationFrame(()=>revealSetup());if(loader){loader.classList.add('is-hidden');setTimeout(()=>loader.remove(),700)}}
async function start(){favicon();setupNav();setTimeout(finishLoader,2600);try{await Promise.all([loadArticles(),loadStaff()])}catch(e){console.error('PPW startup failed:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
const enhancement=document.createElement('script');enhancement.src='ppw-enhancements.js?v=8';document.body.appendChild(enhancement);const interactive=document.createElement('script');interactive.src='ppw-interactive.js?v=7';document.body.appendChild(interactive);
