(()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='ppw-fixes.css?v=11';document.head.appendChild(l);const i=document.createElement('link');i.rel='stylesheet';i.href='ppw-interactive.css?v=5';document.head.appendChild(i)})();
const SUPABASE_URL='https://qyipadinsphoyxotrceo.supabase.co';
const SUPABASE_KEY='sb_publishable_S73dZK9ro03lWDbHFzZhw_5t5pDtGt';
const db=window.supabase?.createClient?.(SUPABASE_URL,SUPABASE_KEY);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const date=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}).toUpperCase()};
const href=a=>`article.html?slug=${encodeURIComponent(a.slug||'')}`;
const img=(a,cls='story-image')=>a.image_url?`<img class="${cls}" src="${esc(a.image_url)}" alt="${esc(a.title||'')}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling&&(this.nextElementSibling.style.display='grid')"><div class="story-placeholder fallback-placeholder" style="display:none">${esc(a.category||'PPW').toUpperCase()}</div>`:`<div class="story-placeholder">${esc(a.category||'PPW').toUpperCase()}</div>`;
const card=a=>`<article class="story-card reveal"><a href="${href(a)}">${img(a)}<div class="story-body"><span class="category-pill">${esc(a.category||'PPW').toUpperCase()}</span><h3>${esc(a.title||'Untitled Article')}</h3><p>${esc(a.excerpt||'Read the latest story from Paw Prints Weekly.')}</p><div class="meta"><span>${esc((a.author||'PPW Staff').toUpperCase())}</span><span>${date(a.published_at)}</span></div></div></a></article>`;
function setupNav(){const toggle=document.getElementById('menuToggle'),nav=document.getElementById('mainNav');if(!nav)return;if(!nav.querySelector('a[href="games.html"]')){const games=document.createElement('a');games.href='games.html';games.textContent='Games';const more=[...nav.querySelectorAll('a')].find(a=>a.textContent.trim().toLowerCase()==='more');more?more.after(games):nav.appendChild(games)}toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('active',open);toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.classList.remove('active');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));const current=document.getElementById('currentDate');if(current)current.textContent=new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'}).toUpperCase()}
let revealObserver;function revealSetup(){const items=document.querySelectorAll('.reveal');if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){items.forEach(e=>e.classList.add('visible'));return}revealObserver ||= new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.08,rootMargin:'0px 0px -30px 0px'});items.forEach(e=>{if(!e.dataset.ppwObserved){e.dataset.ppwObserved='1';revealObserver.observe(e)}})}
function renderFeatured(articles){const el=document.getElementById('featuredArticle');if(!el)return;const chosen=[...articles.filter(a=>a.featured===true),...articles.filter(a=>a.featured!==true)].slice(0,2);if(!chosen.length){el.innerHTML='<div class="empty-card">No featured stories yet.</div>';return}el.classList.add('dual-featured');el.innerHTML=chosen.map((a,i)=>`<article class="featured-card reveal"><a href="${href(a)}">${img(a)}<div class="story-body"><div class="featured-badge">${i?'ALSO FEATURED':"EDITOR'S LEAD"}</div><span class="category-pill">${esc(a.category||'PPW').toUpperCase()}</span><h3>${esc(a.title||'Untitled Article')}</h3><p>${esc(a.excerpt||'Read this story from Paw Prints Weekly.')}</p><div class="meta"><span>${esc((a.author||'PPW Staff').toUpperCase())}</span><span>${date(a.published_at)}</span></div></div></a></article>`).join('')}
const categoryIds={'School News':'cat-school-news','Student Life':'cat-student-life','Sports':'cat-sports','Perspectives':'cat-perspectives','World Events':'cat-world-events','Features':'cat-features','Entertainment & Media':'cat-entertainment-media','Editorial':'cat-editorial'};
function renderCategories(articles){Object.entries(categoryIds).forEach(([cat,id])=>{const el=document.getElementById(id);if(!el)return;const rows=articles.filter(a=>a.category===cat).slice(0,6);el.innerHTML=rows.length?rows.map(card).join(''):`<div class="empty-card">No ${esc(cat.toLowerCase())} stories have been published yet.</div>`})}
async function loadArticles(){const latest=document.getElementById('latestArticles'),featured=document.getElementById('featuredArticle');if(latest)latest.innerHTML='<div class="loading-card">Loading articles...</div>';try{if(!db)throw new Error('Supabase client unavailable');const {data,error}=await db.from('articles').select('id,title,slug,excerpt,category,author,image_url,published_at,featured,tags').eq('status','published').order('published_at',{ascending:false});if(error)throw error;const articles=Array.isArray(data)?data:[];if(latest)latest.innerHTML=articles.length?articles.slice(0,6).map(card).join(''):'<div class="empty-card">No published stories yet.</div>';renderFeatured(articles);renderCategories(articles);revealSetup()}catch(e){console.error('PPW article load failed:',e);if(latest)latest.innerHTML='<div class="empty-card error-card">The newsroom is temporarily unavailable. Please refresh the page.</div>';if(featured)featured.innerHTML='<div class="empty-card error-card">Featured stories could not be loaded.</div>'}}
async function loadStaff(){const el=document.getElementById('staffGrid');if(!el)return;el.innerHTML='<div class="loading-card">Loading staff...</div>';try{if(!db)throw new Error('Supabase client unavailable');const {data,error}=await db.from('staff_members').select('name,role,bio,sort_order').eq('active',true).order('sort_order',{ascending:true});if(error)throw error;if(!data?.length){el.innerHTML='<div class="empty-card">Staff information will appear here soon.</div>';return}el.innerHTML=data.map(m=>`<article class="staff-card reveal"><div class="staff-initial">${esc((m.name||'P').trim().charAt(0).toUpperCase())}</div><div><span class="staff-role">${esc(m.role||'Staff Member')}</span><h3>${esc(m.name||'PPW Staff')}</h3>${m.bio?`<p>${esc(m.bio)}</p>`:''}</div></article>`).join('');revealSetup()}catch(e){console.error('PPW staff load failed:',e);el.innerHTML='<div class="empty-card error-card">Staff information is temporarily unavailable.</div>'}}
function favicon(){if(!document.querySelector('link[rel="icon"]')){const x=document.createElement('link');x.rel='icon';x.type='image/png';x.href='images/tiger.png';document.head.appendChild(x)}}
function finishLoader(){const loader=document.getElementById('ppwLoader');document.body.classList.remove('ppw-loading');document.documentElement.classList.remove('ppw-loader-active');document.body.classList.add('ppw-intro-done');requestAnimationFrame(()=>revealSetup());if(loader){loader.classList.add('is-hidden');setTimeout(()=>loader.remove(),900)}}
async function start(){favicon();setupNav();const started=performance.now();try{await Promise.all([loadArticles(),loadStaff()])}finally{const elapsed=performance.now()-started;setTimeout(finishLoader,Math.max(0,4200-elapsed))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
const enhancement=document.createElement('script');enhancement.src='ppw-enhancements.js?v=6';document.body.appendChild(enhancement);const interactive=document.createElement('script');interactive.src='ppw-interactive.js?v=5';document.body.appendChild(interactive);