-- PPW article image storage
-- Run this once in the Supabase SQL Editor.
-- NEVER put the Supabase secret key in your website.

insert into storage.buckets (id, name, public)
values ('article-images', 'article-images', true)
on conflict (id) do update set public = true;

-- Existing storage policies
create policy "PPW public can view article images"
on storage.objects for select to public
using (bucket_id = 'article-images');

create policy "PPW admins can upload article images"
on storage.objects for insert to authenticated
with check (bucket_id = 'article-images');

create policy "PPW admins can update article images"
on storage.objects for update to authenticated
using (bucket_id = 'article-images')
with check (bucket_id = 'article-images');

create policy "PPW admins can delete article images"
on storage.objects for delete to authenticated
using (bucket_id = 'article-images');

-- Multiple photos per article. The existing articles.image_url remains the cover image.
create table if not exists public.article_images (
    id bigint generated by default as identity primary key,
    article_id bigint not null references public.articles(id) on delete cascade,
    image_url text not null,
    sort_order integer not null default 0,
    alt_text text,
    created_at timestamptz not null default now()
);

alter table public.article_images enable row level security;

drop policy if exists "PPW public can view article gallery" on public.article_images;
drop policy if exists "PPW admins can add article gallery images" on public.article_images;
drop policy if exists "PPW admins can update article gallery images" on public.article_images;
drop policy if exists "PPW admins can delete article gallery images" on public.article_images;

create policy "PPW public can view article gallery"
on public.article_images for select
to anon, authenticated
using (true);

create policy "PPW admins can add article gallery images"
on public.article_images for insert
to authenticated
with check (true);

create policy "PPW admins can update article gallery images"
on public.article_images for update
to authenticated
using (true)
with check (true);

create policy "PPW admins can delete article gallery images"
on public.article_images for delete
to authenticated
using (true);
